Reimplement Signup Page
gtubt/gtubt-mobile pull request #108
Opened 2021-04-18 10:14 UTC by yusufferdogan

2021-04-18 11:27 UTC, yusufferdogan commented
![](https://github.trello.services/images/mini-trello-icon.png) [SignUp page, login page gibi olmali (implementation)](https://trello.com/c/fTWPbwBD/221-signup-page-login-page-gibi-olmali-implementation)

2021-04-18 12:35 UTC, gurolcay commented on gtubt/lib/ui/utils/notification.dart
> +      //borderRadius: 8,
bunlari burada yapmayalim

2021-04-18 12:35 UTC, gurolcay commented
@yusufferdogan conflict var onu cozer misin? bir de notifactionlari duzeltelim

2021-04-18 17:16 UTC, onurccn approved these changes

2021-04-19 19:17 UTC, gurolcay requested changes
it doesn't look like design. please check figma

2021-05-06 07:16 UTC, gurolcay requested changes

2021-05-06 07:16 UTC, gurolcay commented on gtubt/lib/ui/pages/signup_page.dart
> +              message: "Sign Up Successful");
burada basarili kayit oldu diyemeyiz.henuz yeni gonderdik. alttaki if icinde success mesajini vermeliyiz. Burada islemin devam ettigine dair bilgi vermeliyiz. `Registering`  gibi.

2021-05-06 07:16 UTC, gurolcay commented on gtubt/lib/ui/pages/signup_page.dart
> +                        _createCheckBox(
`create` yerine `build` kullanalim. alttakinde de ayni sekilde.

2021-05-06 07:16 UTC, gurolcay commented on gtubt/lib/ui/pages/signup_page.dart
> +                              child: _createLoginButton(),
create yerine build kullanalim. alttakinde de ayni sekilde.

2021-05-06 07:16 UTC, gurolcay commented on gtubt/lib/ui/pages/signup_page.dart
> +  bool _value1 = false;
neyin valuesu? daha anlamli degisken isimleri kullanalim.

2021-05-06 07:16 UTC, gurolcay commented on gtubt/lib/ui/pages/signup_page.dart
> +                            1),
bu gonderilen 1 ve 2 ne anlama geliyor?

2021-05-08 22:19 UTC, gurolcay approved these changes

2021-05-08 22:19 UTC, merged