Accept Turkish characters
gtubt/gtubt-mobile pull request #111
Opened 2021-04-25 20:32 UTC by yusufferdogan

2021-04-25 20:33 UTC, yusufferdogan commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create Account icinde turkce karakterleri de kabul etmemiz lazim.](https://trello.com/c/v9DrhAdt/243-create-account-icinde-turkce-karakterleri-de-kabul-etmemiz-lazim)

2021-04-26 12:57 UTC, gurolcay requested changes

2021-04-26 12:57 UTC, gurolcay commented on gtubt/lib/ui/utils/validators.dart
> +      r"^[a-zA-Z0-9-ğüşıöçĞÜŞİÖÇ.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-ğüşıöçĞÜŞİÖÇ]+(?:\.[a-zA-Z0-9-]+)*$");
email never has turkish chars.

2021-04-26 13:25 UTC, yusufferdogan commented on gtubt/lib/ui/utils/validators.dart
> +      r"^[a-zA-Z0-9-ğüşıöçĞÜŞİÖÇ.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-ğüşıöçĞÜŞİÖÇ]+(?:\.[a-zA-Z0-9-]+)*$");
düzelltim hocam

2021-04-26 17:55 UTC, gurolcay approved these changes

2021-04-26 17:55 UTC, merged