257 replace deprecated classes
gtubt/gtubt-mobile pull request #115
Opened 2021-05-03 17:36 UTC by aErgani

2021-05-03 17:43 UTC, alikaradogan approved these changes

2021-05-03 17:51 UTC, gurolcay requested changes

2021-05-03 17:51 UTC, gurolcay commented on gtubt/lib/ui/pages/login_form.dart
> +        style: TextButton.styleFrom(primary: ColorSets.barBackgroundColor),
style klasoru altina `button_styles.dart` adinda bir dosya acip bunlari ortak bir yere cekebilir miyiz?

2021-05-03 17:51 UTC, gurolcay commented on gtubt/lib/ui/pages/profile_page.dart
> +                    style: ElevatedButton.styleFrom(
bu da ayni sekilde.

2021-05-03 17:51 UTC, gurolcay commented on gtubt/lib/ui/pages/signup_page.dart
> +        style: ElevatedButton.styleFrom(
bu da ayni sekilde

2021-05-03 18:32 UTC, YasirNacak approved these changes

2021-05-04 06:37 UTC, gurolcay requested changes

2021-05-04 06:37 UTC, gurolcay commented on gtubt/lib/ui/blocs/calendar_bloc/calendar_bloc.dart
> -  final UserService _userService = UserService();
bu kullanilacak burada kalsin.

2021-05-04 06:37 UTC, gurolcay commented on gtubt/lib/ui/blocs/ticket_bloc/ticket_bloc.dart
> -  final UserService _userService = UserService();
bu da kullanilacak burada kalsin,

2021-05-04 16:38 UTC, alikaradogan commented on gtubt/lib/service/ticket.dart
> +    throw UnimplementedError();
Bunlara gerçekten gerek var mı? Şu anda implement ediyorum merge esnasında conflict çıkaracak. Bence bir hafta daha hata fırlatmasa bir şey kaybetmeyiz.

2021-05-07 03:35 UTC, alikaradogan commented
![](https://github.trello.services/images/mini-trello-icon.png) [Flutter'da deprecated olan yerlerin degistirilmesi](https://trello.com/c/xCphrRs1/257-flutterda-deprecated-olan-yerlerin-degistirilmesi)

2021-05-08 13:08 UTC, gurolcay approved these changes

2021-05-08 13:09 UTC, merged