null-safety: Migrate to sound null safety
gtubt/gtubt-mobile pull request #116
Opened 2021-05-05 21:42 UTC by alikaradogan

## What does this PR do?

- Migrates project to sound null safety.

2021-05-06 07:09 UTC, gurolcay commented on gtubt/lib/models/user.dart
> -  @JsonKey(nullable: true)
burasi ilginc geldi. `@JsonKey(nullable: true)` kaldirdik. Peki backend bunu donmez ise ne olacak? nasil davranis gosteriyor? veya `phone` donmedi. deserialize ederken patlamasin?

2021-05-06 14:42 UTC, alikaradogan commented on gtubt/lib/models/user.dart
> -  @JsonKey(nullable: true)
Flutter null safety ile bunlara gerek yok dedi. Artık bunlar tanımı itibariyle nullable.

2021-05-07 03:35 UTC, alikaradogan commented
![](https://github.trello.services/images/mini-trello-icon.png) [Null safety migration](https://trello.com/c/JXxnkhXB/266-null-safety-migration)

2021-05-14 07:28 UTC, gurolcay requested changes
conflict

2021-05-30 13:25 UTC, onurccn approved these changes

2021-05-30 23:10 UTC, alikaradogan commented
Please merge this PR before any other so we can have people writing/changing their code in respect to null-safety. @gurolcay

2021-05-31 18:05 UTC, gurolcay approved these changes

2021-05-31 18:05 UTC, merged