get events from endpoint
gtubt/gtubt-mobile pull request #120
Opened 2021-05-29 17:19 UTC by yusufferdogan

Dummy data removed. We get data from API.
1) I changed getAll method because it's not work properly. I rewrite it like news service
2) To run it properly the date must be like this yyyy-MM-dd
3) To run it properly valid image URL must be provided
? Event Model exist image URL, but  calendar page does not exist

2021-05-29 18:18 UTC, gurolcay requested changes

2021-05-29 18:18 UTC, gurolcay commented on gtubt/lib/service/event.dart
> +      apiResponse.body = body.reversed.toList();
date'e gore siralama yapalim. bu her zaman istedigimiz sirayi vermez.

2021-05-29 18:18 UTC, gurolcay commented on gtubt/lib/service/event.dart
> +        throw EventException.message('${apiResponse.message}');
eskisi gibi kalsin

2021-05-29 18:18 UTC, gurolcay commented on gtubt/lib/ui/blocs/calendar_bloc/calendar_bloc.dart
> +    } catch (e) {
burada servis icinde firlatilan hatayi yakalamalisin ve onun error mesajini `EventsError` state'ine vermelisin

2021-05-30 13:12 UTC, onurccn commented on gtubt/lib/service/event.dart
> +      apiResponse.body = body.reversed.toList();
genellikle pagination ve order server tarafinda yapilir. UI da islemek istedigimize emin miyiz?

2021-05-30 13:23 UTC, onurccn approved these changes

2021-05-30 20:05 UTC, gurolcay commented on gtubt/lib/service/event.dart
> +      apiResponse.body = body.reversed.toList();
dedigin dogru buradaki reserved olayini kaldiralim. sirali gelmiyorsa backend'de halledelim bunu

2021-05-31 18:05 UTC, gurolcay requested changes
please check null safety

2021-06-03 14:08 UTC, alikaradogan commented on gtubt/lib/ui/blocs/calendar_bloc/calendar_bloc.dart
> +    } catch (e) {
Problem hala mevcut. Catch yapmadan once `on` ile servisin kendi hatasini yakalaman gerekiyor.

2021-06-03 14:10 UTC, alikaradogan requested changes

2021-06-03 14:10 UTC, alikaradogan commented on gtubt/lib/ui/blocs/calendar_bloc/calendar_bloc.dart
> +    } catch (e) {
Ornek 
```
} on EventError {
    yield EventsError(EventError...)...
```

gibi

2021-06-05 12:58 UTC, gurolcay approved these changes

2021-06-05 12:58 UTC, merged