177 profile image upload
gtubt/gtubt-mobile pull request #123
Opened 2021-05-31 20:56 UTC by hybrayhem

2021-05-31 20:59 UTC, alikaradogan requested changes
Conflicts!

2021-05-31 21:48 UTC, onurccn requested changes

2021-05-31 21:48 UTC, onurccn commented on gtubt/lib/ui/blocs/user_bloc/user_bloc.dart
> +        yield UserState.failure("Photo can not be changed.");
exception olmadigi durumda finally blogunda normal userstate i donulmeli

2021-05-31 21:48 UTC, onurccn commented on gtubt/lib/ui/pages/profile_page.dart
> +    if (context.read<AppbarBloc>().state.editMode) {
edit mode da olmamiza gerek yok bu islem icin. Sayfa state inde conflicte sebep olabilir

2021-06-02 19:21 UTC, onurccn approved these changes

2021-06-02 19:22 UTC, onurccn commented
@hybrayhem user la ilgili bi fiximi ezmisiz master merge le, onu duzelttim. Bir de edit iconu biraz kafa karistirici duruyodu ui da simdilik bos kalsin orasi.

2021-06-02 19:24 UTC, onurccn commented
![](https://github.trello.services/images/mini-trello-icon.png) [profile resim yuklenmesi icin arayuz calismasinin yapilmasi](https://trello.com/c/OWnhx4t0/177-profile-resim-yuklenmesi-icin-arayuz-calismasinin-yapilmasi)

2021-06-02 19:31 UTC, hybrayhem commented
> @hybrayhem user la ilgili bi fiximi ezmisiz master merge le, onu duzelttim. Bir de edit iconu biraz kafa karistirici duruyodu ui da simdilik bos kalsin orasi.

Tamamdır. Edit ikonu tasarımda öyleydi değişene kadar boş kalabilir burada.

2021-06-05 11:41 UTC, gurolcay approved these changes

2021-06-05 11:42 UTC, merged