base cloud function route for pulling news articles
gtubt/gtubt-mobile pull request #22
Opened 2020-03-12 20:10 UTC by YasirNacak

2020-03-16 18:20 UTC, onurccn requested changes

2020-03-16 18:20 UTC, onurccn commented on cloud-functs/functions/index.js
> +				// TODO(yasir): give a better response than this
console.log bırakmayalım

2020-03-16 18:51 UTC, YasirNacak commented on cloud-functs/functions/index.js
> +				// TODO(yasir): give a better response than this
catch durumlarinda firebase console'dan anlayabilir miyiz problemi? yoksa onlari birakayim mi?

2020-03-17 11:36 UTC, gurolcay approved these changes

2020-03-17 11:36 UTC, merged