#100 PATCH and DELETE endpoints for user controller
gtubt/gtubt-mobile pull request #42
Opened 2020-04-27 16:26 UTC by onurccn

- added patch and delete endpoints for user controller

2020-04-27 16:57 UTC, YasirNacak requested changes

2020-04-27 16:57 UTC, YasirNacak commented on cloud-functions/controllers/user.js
> +      console.log('User deleted successfully', user)
basarili oldugu durumda console.log yapmamiza gerek yok

2020-04-27 16:57 UTC, YasirNacak commented on cloud-functions/controllers/user.js
> +    Object.assign(user, userBody)
assign etmeden once POST'ta yaptigimiz gibi isim ve soyismi TitleCase'e cevirip, telefon numarasini sanitize etmemiz lazim

2020-04-27 16:59 UTC, YasirNacak commented
pr acmadan once `npm run lint` calistirip style guide'a uyup uymadigini gorebilirsin

2020-04-27 17:33 UTC, onurccn commented on cloud-functions/controllers/user.js
> +      console.log('User deleted successfully', user)
Adami siliyoz artik kimi silmisiz kimi silmemisiz bilelim

2020-04-27 17:35 UTC, onurccn commented
> pr acmadan once `npm run lint` calistirip style guide'a uyup uymadigini gorebilirsin

bunu calistiramadim local environmentimda hata veriyo cozemedim. Formatladim dosyayi tekrardan

2020-04-27 17:44 UTC, YasirNacak requested changes
linter bu hatalari verdi bende

128:7   error  It's not necessary to initialize 'user' to undefined  no-undef-init
156:25  error  Unexpected trailing comma                             comma-dangle

Windows konsolu degil de WSL konsolu ile calistirmayi dene linteri.

2020-04-27 17:52 UTC, onurccn commented
> linter bu hatalari verdi bende
> 
> 128:7 error It's not necessary to initialize 'user' to undefined no-undef-init
> 156:25 error Unexpected trailing comma comma-dangle
> 
> Windows konsolu degil de WSL konsolu ile calistirmayi dene linteri.

o commayi bilerek koyduydum bi de...

2020-04-27 18:21 UTC, YasirNacak approved these changes

2020-04-27 18:47 UTC, gurolcay commented on cloud-functions/controllers/user.js
> +        userBody.phone = libphonenumber.parsePhoneNumberFromString(userBody.phone, 'TR').formatNational()
burasi hata verebilir mi?

2020-05-02 19:14 UTC, gurolcay commented on cloud-functions/controllers/user.js
> +        userBody.phone = libphonenumber.parsePhoneNumberFromString(userBody.phone, 'TR').formatNational()
@onurccn

2020-05-02 19:47 UTC, onurccn commented on cloud-functions/controllers/user.js
> +        userBody.phone = libphonenumber.parsePhoneNumberFromString(userBody.phone, 'TR').formatNational()
Ne hatası? Eğer id gelmezse zaten express kabul etmeyecek

2020-05-03 14:23 UTC, gurolcay commented on cloud-functions/controllers/user.js
> +        userBody.phone = libphonenumber.parsePhoneNumberFromString(userBody.phone, 'TR').formatNational()
tamamdir

2020-05-03 14:23 UTC, gurolcay approved these changes

2020-05-03 14:23 UTC, merged