Profile page added with user credential functionality.
gtubt/gtubt-mobile pull request #6
Opened 2019-10-15 06:49 UTC by askaradogan

Profile page added with user credential functionality.

2019-10-15 06:52 UTC, gurolcay commented on sample/lib/ui/pages/profile_page.dart
> +    color: Color(0xFF4E72CB),
renkleri boyle kullanmayalim. `lib > ui` altina `utils` diye bir klasor acalim color_sets.dart diye bir dosyamizda ColorSets diye bir sinifta bu renkleri tanimlayalim

2019-10-15 06:54 UTC, gurolcay commented on sample/lib/ui/pages/profile_page.dart
> +        color: Color(0xFF4E72CB),
14. satir ile ayni

2019-10-15 07:43 UTC, gurolcay commented on sample/lib/ui/pages/profile_page.dart
> +  Widget _ProfileImage() {
fonksiyonlara buyuk harfle baslamak yerine kucuk harfle baslamak daha iyi olacaktir

2019-10-15 07:46 UTC, gurolcay commented on sample/lib/ui/pages/profile_page.dart
> +              _FullName(_fullname),
zaten sinif icinde tanimli degiller mi? neden parametro olarak gonderdik

2019-10-15 18:47 UTC, onurccn requested changes
User modelini bu sayfada kullanmalıyız. Bloc pattern i kullanmasak bile en azından modelleri entegre edelim

2019-10-16 20:31 UTC, gurolcay commented on sample/lib/ui/pages/main_page.dart
> +          _selectedIndex = state.currentPage;
PageBloc kullanirken neden bu islem burada yapildi?

2019-10-16 20:31 UTC, gurolcay commented on sample/lib/ui/pages/main_page.dart
> +          _selectedIndex = state.currentPage;
@onurccn

2019-10-16 20:35 UTC, gurolcay commented on sample/lib/ui/pages/profile_page.dart
> +        child: Padding(
Container Altinda bir padding widget'i kullanmaya gerek yok zaten kendi icinde padding degiskeni aliyor.
Bu padding ile baslayan yer asagidaki gibi olmali
```
Container(
                    padding: EdgeInsets.only(8.0),
                    child: Text(
                      name,
                      style: _nameTextStyle,
                    ),
                  ),
```

2019-10-16 20:37 UTC, gurolcay commented on sample/lib/ui/pages/profile_page.dart
> +          Padding(
Container ile sarmala

2019-10-16 20:37 UTC, gurolcay commented on sample/lib/ui/pages/profile_page.dart
> +          Padding(
Container ile sarmala

2019-10-16 20:38 UTC, gurolcay commented on sample/lib/ui/pages/profile_page.dart
> +          Padding(
Container ile sarmala

2019-10-16 20:38 UTC, gurolcay commented on sample/lib/ui/pages/profile_page.dart
> +          Padding(
Container ile sarmala

2019-10-16 20:38 UTC, gurolcay commented on sample/lib/ui/pages/profile_page.dart
> +          Padding(
container

2019-10-16 20:38 UTC, gurolcay commented on sample/lib/ui/pages/profile_page.dart
> +          Padding(
container

2019-10-16 20:38 UTC, gurolcay commented on sample/lib/ui/pages/profile_page.dart
> +          Padding(
container

2019-10-16 20:39 UTC, gurolcay commented on sample/lib/ui/pages/profile_page.dart
> +          Padding(
container

2019-10-16 20:42 UTC, gurolcay commented on sample/lib/ui/pages/profile_page.dart
> +              child: Padding(
padding widget'ina gerek yok container icinde zaten var

2019-10-16 20:42 UTC, gurolcay commented on sample/lib/ui/pages/profile_page.dart
>                child: Padding(
padding widget'ina gerek yok container icinde zaten var

2019-10-16 20:42 UTC, gurolcay commented on sample/lib/ui/pages/profile_page.dart
>                child: Padding(
padding widget'ina gerek yok container icinde zaten var

2019-10-16 20:45 UTC, gurolcay commented on sample/lib/ui/style/color_sets.dart
> +class ColorSets {
@ahmetergani `GtuBtColors` adinda bir sinif olusturmus. ben seninde yaptigini farketmemisim. dev'i bu branch'e rebase edip `GtuBtColors` i kaldirip `ColorSets` ile merge edelim

2019-10-30 19:32 UTC, gurolcay commented on sample/lib/ui/blocs/page_bloc/page_event.dart
> +// import 'page_state.dart';
Kullanilmiyorsa silelim

2019-10-30 19:33 UTC, gurolcay commented on sample/lib/main.dart
> +        builder: (context) => PageBloc(),
format degisikliklerini olabildigince baska commit icinde yapalim bu sekilde ne degismis diye anlamak icin ugrasiyoruz.

2019-10-30 19:34 UTC, gurolcay commented on sample/lib/ui/blocs/user_bloc/user_event.dart
> +// import 'user_state.dart';
kullanilmiyorsa silelim

2019-10-30 19:35 UTC, gurolcay commented on sample/lib/ui/pages/profile_page.dart
> +// import 'package:GTUBT/main.dart';
kullanilmiyorsa silelim

2019-10-30 19:36 UTC, gurolcay commented on sample/lib/ui/pages/profile_page.dart
> +    color: Colors.black,
buradaki renkleri de `ColorSets` sinifindan almasi iyi olacaktir bence.

2019-10-30 20:25 UTC, merged