#139 cards formatted with time ago library
gtubt/gtubt-mobile pull request #60
Opened 2020-11-12 12:32 UTC by yusufferdogan

2020-11-12 17:14 UTC, onurccn requested changes

2020-11-12 17:14 UTC, onurccn commented on sample/lib/ui/pages/home_page.dart
> +import '../utils/time_ago_formatter.dart';
Importlari relative degil absolute path olarak alalim. Digerleriyle ayni gozuksun.

2020-11-12 17:25 UTC, yusufferdogan commented on sample/lib/ui/pages/home_page.dart
> +import '../utils/time_ago_formatter.dart';
Değiştirdim.

2020-11-12 17:34 UTC, onurccn commented on sample/lib/ui/pages/home_page.dart
> +import '../utils/time_ago_formatter.dart';
Relative olanı kaldırmamışsın sanırım. Home page de de var aynısı. Post da değişiklik görüyorum sadece doğru mu?

2020-11-12 17:44 UTC, yusufferdogan commented on sample/lib/ui/pages/home_page.dart
> +import '../utils/time_ago_formatter.dart';
onu unutmuşum şuan değiştirdim olmuş mu acaba ?

2020-11-12 17:47 UTC, onurccn commented on sample/lib/ui/pages/home_page.dart
> +import '../utils/time_ago_formatter.dart';
Oldu olacak. Posttan relative olani kaldirmamissin hala :D

2020-11-12 17:54 UTC, yusufferdogan commented on sample/lib/ui/pages/home_page.dart
> +import '../utils/time_ago_formatter.dart';
o önceki commit de sanırım.

2020-11-12 18:46 UTC, gurolcay commented on sample/lib/ui/pages/post_page.dart
> +import '../utils/time_ago_formatter.dart';
bu importu duzeltebilir miyiz?

2020-11-12 19:34 UTC, yusufferdogan commented on sample/lib/ui/pages/post_page.dart
> +import '../utils/time_ago_formatter.dart';
umarım ki bu sefer olmuştur :)

2020-11-13 12:48 UTC, YasirNacak approved these changes

2020-11-13 17:47 UTC, gurolcay approved these changes

2020-11-13 17:47 UTC, merged