#170 Remove Form Box Container
gtubt/gtubt-mobile pull request #61
Opened 2020-11-13 08:42 UTC by gokceerer

-Changed form_box_container content from box decoration to input decoration
-Added decorations to form inputs
-Changed DropdownButton to DropdownButtonFormField

2020-11-13 12:49 UTC, YasirNacak approved these changes

2020-11-13 17:00 UTC, gurolcay commented
@gokceerer isim soyisim gibi seyleri ingilizce yapalim

2020-11-13 17:01 UTC, gurolcay commented on sample/lib/ui/pages/signup_page.dart
> +        /*Container(
bu neden yorum satirinda? ihtiyac yoksa kaldiralim

2020-11-13 17:02 UTC, gurolcay commented on sample/lib/ui/pages/signup_page.dart
> +        shape: new RoundedRectangleBorder(
new keyword'u zorunlu degil. kullanmayalim

2020-11-13 17:03 UTC, gurolcay commented on sample/lib/ui/pages/signup_page.dart
> +                        Container(
bu containerlar gerekli ise bunlari form icine alalim.

2020-11-13 20:01 UTC, gurolcay requested changes

2020-11-13 20:01 UTC, gurolcay commented on sample/lib/ui/pages/signup_page.dart
> +          borderRadius: new BorderRadius.circular(10.0),
new

2020-11-15 14:57 UTC, gurolcay approved these changes

2020-11-15 14:57 UTC, merged