26 ticket page ui and ticket model
gtubt/gtubt-mobile pull request #63
Opened 2020-11-13 17:44 UTC by hybrayhem

2020-11-15 15:00 UTC, gurolcay approved these changes

2020-11-15 15:01 UTC, YasirNacak approved these changes

2020-11-15 15:02 UTC, gokceerer approved these changes

2020-11-21 20:20 UTC, gurolcay commented on sample/lib/ui/pages/ticket_page.dart
> +    return ListView.builder(
burada bir scaffold vs bir seye ihtiyacimiz yok mu?

2020-11-21 20:21 UTC, gurolcay commented on sample/lib/ui/pages/ticket_page.dart
> +    return ListView.builder(
localimde route'a ekledigimde bu sayfayi goremiyorum.

2020-11-25 10:37 UTC, gurolcay requested changes
build metoduna bakilmali

2020-11-25 18:44 UTC, gurolcay approved these changes

2020-11-25 18:44 UTC, merged