171 App Name and bundleID change
gtubt/gtubt-mobile pull request #68
Opened 2020-11-21 20:35 UTC by hybrayhem

2020-11-21 21:05 UTC, gurolcay commented
we have change google services file after merge

2020-11-21 21:07 UTC, gurolcay requested changes
conflict

2020-11-25 19:43 UTC, onurccn commented
Android ve ios kismindaki dosyalari yeniden flutter komutuyla olusturduk dimi?

2020-11-25 20:04 UTC, hybrayhem commented
> Android ve ios kismindaki dosyalari yeniden flutter komutuyla olusturduk dimi? 

rename package'ı ve bu rehberi kullandım:
https://flutter.dev/docs/deployment/android 
Android çalışıyor, ios denenmedi.

2020-11-29 13:14 UTC, gurolcay approved these changes

2020-11-29 13:18 UTC, gokceerer approved these changes

2020-11-29 13:19 UTC, merged

2020-11-29 13:20 UTC, gurolcay commented
Localde build aldim codemagic neden kirildi ayrica degerlendirilecek. blocker oldugu icin merge 2 review'de merge edildi.