#121 added user update endpoint and initialize user
gtubt/gtubt-mobile pull request #71
Opened 2020-12-01 15:02 UTC by yusufferdogan

2020-12-10 17:13 UTC, onurccn requested changes

2020-12-10 17:13 UTC, onurccn commented on sample/lib/ui/blocs/user_bloc/user_bloc.dart
> +      if (currentState.editMode == true) {
edit mode a gecerken update ediyoruz gibi gozukuyo bu. Edit mode dan cikarken update ediyo olmamiz gerekiyo. Update sonrasi bize bi user da donmesi gerekiyo bu endpointin, o user i currentstate teki user a da atamamiz gerek.

2020-12-10 17:13 UTC, onurccn commented on sample/lib/ui/blocs/user_bloc/user_state.dart
> +  User updatedUser;
Bunu nerede kullaniyoruz?

2020-12-10 17:13 UTC, onurccn commented on sample/lib/ui/pages/login_form.dart
> +            BlocProvider.of<UserBloc>(context).add(GetUser());
GetUser i state.initial da yapmamiz gerekiyo. Ama tam emin degilim. Bunu konusalim. @gurolcay

2020-12-10 17:13 UTC, onurccn commented on sample/lib/ui/pages/main_page.dart
> +    final userProvider = BlocProvider.of<UserBloc>(context);
userBloc aslinda burda elimizdeki obje. BlocProvider dan elde ediyoruz sadece.

2020-12-29 20:48 UTC, closed without merging

2020-12-29 20:49 UTC, gurolcay commented
baska iste pr da ele alindi