#185 make date fields datetime
gtubt/gtubt-mobile pull request #77
Opened 2020-12-25 13:28 UTC by yusufferdogan

2020-12-30 18:32 UTC, gurolcay requested changes

2020-12-30 18:32 UTC, gurolcay commented on gtubt/lib/ui/pages/home_page.dart
> +import 'package:GTUBT/models/post.dart';
bu dosyayi kaldirdik. dev branch'ini bu branch'e merge edip pr'i gunceller misin?

2020-12-31 13:47 UTC, yusufferdogan commented on gtubt/lib/ui/pages/home_page.dart
> +import 'package:GTUBT/models/post.dart';
Yaptım olmuş mu ?

2021-01-01 18:17 UTC, onurccn approved these changes

2021-01-02 13:52 UTC, gurolcay approved these changes

2021-01-03 13:53 UTC, merged