#198 ticket page refactor getting data with backend call
gtubt/gtubt-mobile pull request #85
Opened 2021-02-19 13:32 UTC by yusufferdogan

2021-02-20 15:35 UTC, gurolcay requested changes

2021-02-20 15:35 UTC, gurolcay commented on gtubt/lib/ui/pages/ticket_page.dart
> +          print('snapshot.data::::::::::::::::::${snapshot.data}');
?

2021-02-20 15:35 UTC, gurolcay commented on gtubt/lib/ui/pages/ticket_page.dart
> +  Future<List<Ticket>> getAll() async {
bu metot burada olmamali. `lib>service` klasoru altina yeni bir servis servis sinifi yazilmali ve oradan bu bilgilerin gelmesi saglanmali. Ayrica bu datalarin cekilmesi kismi icin bloc pattern kullanilmali.

2021-02-22 13:28 UTC, onurccn requested changes

2021-02-22 13:28 UTC, onurccn commented on gtubt/lib/ui/pages/ticket_page.dart
> +      listener: (context, state) {},
Burda listenerla bisey yapmayi planliyor muyuz? Child i da builder zaten, bu gibi build methodlarina Direk BlocBuilder verelim, hem builder hem listener cidden gerekliyse de BlocConsumer i kullanalim derim.

2021-02-22 13:28 UTC, onurccn commented on gtubt/lib/ui/blocs/ticket_bloc/ticket_state.dart
> +  final List<Ticket> tickets;
Servisten left yerine right gelirse burda nasil bi state donmeyi dusunuyoruz?

2021-02-22 13:28 UTC, onurccn commented on gtubt/lib/ui/routes.dart
> +    TICKET_URL: (context) => BlocProvider(
Bu seperation i begendim 👯

2021-02-22 18:16 UTC, gurolcay commented on gtubt/lib/ui/pages/ticket_page.dart
> +      listener: (context, state) {},
simdilik ihtiyac yok aslinda. ancak ileride kullanilabilir diye yazmistim. Burayi BlocConsumer olarak degistiriyorum.

2021-02-22 18:17 UTC, gurolcay commented on gtubt/lib/ui/blocs/ticket_bloc/ticket_state.dart
> +  final List<Ticket> tickets;
@yusufferdogan burayi her ikisini karsilayacak sekilde tasarlar misin?

2021-02-28 11:10 UTC, YasirNacak approved these changes
👍

2021-02-28 14:02 UTC, onurccn approved these changes

2021-02-28 19:30 UTC, gurolcay approved these changes

2021-02-28 19:31 UTC, merged