201: added profile delete button
gtubt/gtubt-mobile pull request #86
Opened 2021-02-26 09:13 UTC by gokceerer

2021-02-28 10:58 UTC, gurolcay commented on gtubt/lib/ui/blocs/user_bloc/user_bloc.dart
> +          userService.delete(userService.currentUser.id);
await ile bekleyip bu islemin basarili bir sekilde gerceklestigini beklemeliyiz. ayrica oncelikle firebase uzerinde islemi gerceklestirmeli ve hata alinmamasi durumunda kendi db'mizden kullaniciyi silmemiz gerekli

2021-02-28 10:58 UTC, gurolcay commented on gtubt/lib/ui/blocs/user_bloc/user_bloc.dart
> +          Navigator.pushReplacementNamed(event.context, LOGIN_URL);
routing'i burada cozmemeliyiz.

2021-02-28 10:58 UTC, gurolcay commented on gtubt/lib/ui/blocs/user_bloc/user_bloc.dart
> +    else if(event is OnAccountDeletion){
Burada yapilan islem AuthenticationBloc uzerinde gerceklestirilmeli ve AuthenticationState guncellenmeli

2021-02-28 10:58 UTC, gurolcay commented on gtubt/lib/ui/blocs/user_bloc/user_bloc.dart
> +          Navigator.pushReplacementNamed(event.context, LOGIN_URL);
Burada geri yaparsa authenticate oldugu andaki datayi georebilecek. Bunun yerine `pushNamedAndRemoveUntil` ile routing yapmamiz lazim.

2021-02-28 10:58 UTC, gurolcay commented on gtubt/lib/ui/pages/profile_page.dart
> +  final TextStyle _nameTextStyle = TextStyles.subtitle1.copyWith(height: 1.4, color: ColorSets.defaultTextColor, letterSpacing: 0, fontWeight: FontWeight.w500);
bu satir cok uzun formatlama yapar misin?

2021-02-28 10:58 UTC, gurolcay commented on gtubt/lib/ui/pages/profile_page.dart
> +      form =  TextFormField(
bir bosluk fazla

2021-02-28 10:58 UTC, gurolcay commented on gtubt/lib/ui/pages/profile_page.dart
> +      form =  TextFormField(
ayrica buradaki if else icersinde sanki ayni kod var. TexFormField icin kod tekrarindan kacabiliriz gibi geldi.

2021-02-28 10:58 UTC, gurolcay commented on gtubt/lib/ui/pages/profile_page.dart
> +      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
bu shape'i tum popup dialoglarimiz icin kullanacaksak bunu ortak bir yere alip oradan kullanabiliriz.

2021-02-28 10:58 UTC, gurolcay commented on gtubt/lib/ui/pages/profile_page.dart
> +                      RaisedButton(
butonlar icin, `Dialog` un `actions`ini kullamamis olmamizin nedeni tamamen tasarimsal mi?

2021-02-28 11:13 UTC, gurolcay requested changes
authentication bloc ile yapilmali, hatta authentication bloc ve user bloc ile birlikte yapilmali. biri digerini tetikleyebilir.

2021-02-28 11:16 UTC, onurccn commented on gtubt/lib/ui/blocs/user_bloc/user_bloc.dart
> +          Navigator.pushReplacementNamed(event.context, LOGIN_URL);
Burda logine mi ana sayfaya mi donmemiz gerekli?

2021-02-28 11:20 UTC, onurccn commented on gtubt/lib/ui/pages/profile_page.dart
> +      form =  TextFormField(
controller farki var aralarinda, controller i direk olusturmuyoruz editte degilsek. Her seferinde yaratmak ister miyiz if e girmemek icin emin degilim. Test edilebilr

2021-02-28 11:22 UTC, onurccn commented on gtubt/lib/ui/pages/profile_page.dart
> +            child: formWidget(EmailChanged(), email, "E-mail"),
Bu container icerisinde paddingleri kaldirmisiz sadece child kullaniyoruz artik anlasilan, Container widgetini hepten kaldirip formWidget i kullanabilir miyiz burda?

2021-02-28 11:25 UTC, gurolcay commented on gtubt/lib/ui/pages/profile_page.dart
> +      form =  TextFormField(
controller uretmek icin if kalabilir, sadece TextFormField bir tane olabilir gibi geldi.

2021-02-28 11:25 UTC, onurccn commented on gtubt/lib/ui/pages/profile_page.dart
> +                         //_userBloc.userService.delete(user.email);
Yorumlari silebiliriz

2021-03-08 09:10 UTC, gokceerer commented on gtubt/lib/ui/blocs/user_bloc/user_bloc.dart
> +          Navigator.pushReplacementNamed(event.context, LOGIN_URL);
Kullanıcı hesabını sildiğinde sanki logine dönmesi daha mantıklı sanki ya çoğu uygulama öyle yönlendiriyo genelde

2021-03-08 09:11 UTC, gokceerer commented on gtubt/lib/ui/pages/profile_page.dart
> +      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
Uygulama tasarımında tek pop-up görünüyor şu an ya gerekince bu tasarımı mı kullanırız bilemiyorum

2021-03-08 09:12 UTC, gokceerer commented on gtubt/lib/ui/pages/profile_page.dart
> +                      RaisedButton(
Araştırdığımı uyguladım aslında eğer bir avantajı varsa ötekinin üzerine tekrar bakıp düzenleyebilirim

2021-03-08 09:50 UTC, gurolcay commented on gtubt/lib/ui/blocs/user_bloc/user_bloc.dart
> +          Navigator.pushReplacementNamed(event.context, LOGIN_URL);
login required bir uygulama degil. o yuzden anasayfaya atmali.

2021-03-08 10:05 UTC, gurolcay commented on gtubt/lib/ui/pages/profile_page.dart
> +                      RaisedButton(
eger tasarim icin boyle gerekiyorsa boyle kalsin. yoksa diger turlu yapabiliriz.

2021-03-09 17:21 UTC, yusufferdogan approved these changes
👍

2021-04-19 19:09 UTC, alikaradogan commented on gtubt/lib/service/service.dart
> +      auth.User user = container.resolve<auth.User>();
Burada resolve tarafinda type belirtmemize gerek yok. Resolve zaten auth.User instance icin containera bakiyor. Tabi kod daha acik oluyor da diyebilirsiniz.

2021-04-24 20:19 UTC, gurolcay commented on gtubt/lib/service/service.dart
> +      auth.User user = container.resolve<auth.User>();
daha acik olsun. buradaki bir kac kere exception almistim. ondan buna cevirdim.

2021-04-24 20:24 UTC, gurolcay requested changes

2021-04-24 20:24 UTC, gurolcay commented on gtubt/lib/ui/blocs/user_bloc/user_event.dart
> +class OnAccountDeletion extends UserEvent{
silinecek

2021-04-24 20:24 UTC, gurolcay commented on gtubt/lib/ui/blocs/user_bloc/user_state.dart
> +  bool passwordsMatch;
silinecek

2021-04-24 20:31 UTC, gurolcay approved these changes

2021-04-24 20:31 UTC, merged

2021-04-24 20:31 UTC, gurolcay commented
![](https://github.trello.services/images/mini-trello-icon.png) [Profile delete butonu eklenmeli](https://trello.com/c/ROcUAAhJ/201-profile-delete-butonu-eklenmeli)