Add firebase user token to all HTTP requests.
gtubt/gtubt-mobile pull request #97
Opened 2021-03-28 18:01 UTC by alikaradogan

## What does this PR do?

- Includes firebase user token to all HTTP requests if the user logged in.

2021-03-28 18:28 UTC, gurolcay commented on gtubt/lib/service/authentication.dart
> +      KiwiContainer container = KiwiContainer();
bir tane olusturmamizda nasil bir sakinca vardi?

2021-03-28 18:28 UTC, gurolcay commented on gtubt/lib/service/service.dart
> +import 'dart:convert';
bu import sirasi dogru mu?

2021-03-28 19:05 UTC, alikaradogan commented on gtubt/lib/service/authentication.dart
> +      KiwiContainer container = KiwiContainer();
Sakinca yoktu. Fixed.

2021-03-28 19:05 UTC, alikaradogan commented on gtubt/lib/service/service.dart
> +import 'dart:convert';
Degil gibi duruyor. Fixed.

2021-03-28 19:16 UTC, gurolcay approved these changes

2021-04-04 08:52 UTC, gurolcay commented on gtubt/lib/service/service.dart
> +import 'dart:io';
base.dart icerisinde `BaseService` vardi. Neden onun icine yazmadik bunlari

2021-04-04 12:26 UTC, onurccn requested changes

2021-04-04 12:26 UTC, onurccn commented on gtubt/lib/service/authentication.dart
> +      container.clear();
container i clear etmemize gerek var mi? Ayni isimle set ediyosun zaten. Defaultu da singleton mis kutuphanenin. 
container a baska seyler koymaya basladigimizda bu bizi bozar :D

2021-04-04 12:26 UTC, onurccn commented on gtubt/lib/service/authentication.dart
> +      container.registerInstance<auth.User>(_auth.currentUser,
Bu kullanim biraz IoC container mantigina ters gibi geldi bana. Genellikle servisler register edilir diye biliyorum ama static obje tasimak icin de fena durmuyo. @gurolcay sen ne diyosun buna?

2021-04-04 12:26 UTC, onurccn commented on gtubt/lib/service/service.dart
> +      auth.User user = container.resolve("firebaseUser");
named kullanmamiza gerek var mi? Sadece type ile ulasabilsek daha iyi olur. Coklu user gibi bi yapi dusundugumuzu sanmiyorum

2021-04-04 12:26 UTC, onurccn commented on gtubt/pubspec.yaml
> +  kiwi: ^2.1.1
Bunun generator i da varmis sanirim. Servislere cakma bi singleton factory si eklemistik. Onlari bi annotation ile replace edebiliriz gibi duruyo. Bundan sonra ona bakabiliriz.

2021-04-04 12:26 UTC, onurccn commented on gtubt/lib/service/authentication.dart
> +    container.clear();
Yine dedigim gibi tamamini clear etmek yerine ilgili instance i kaldirsak daha iyi olabilir

2021-04-04 17:25 UTC, gurolcay commented on gtubt/lib/service/authentication.dart
> +      container.registerInstance<auth.User>(_auth.currentUser,
tokenResolver icinde getIdToken yapabilmek icin bunu yaptik ama sadece token tasimak bana biraz daha mantikli geliyor.

2021-04-04 17:25 UTC, gurolcay commented on gtubt/pubspec.yaml
> +  kiwi: ^2.1.1
cakma singleton degil ya onlar. normali o :D aslinda onu adam akilli design pattern uygulasak bunlara gerek kalmaz :laughing:

2021-04-11 08:31 UTC, gurolcay approved these changes

2021-04-11 08:31 UTC, merged