[206] profile page edit improvements
gtubt/gtubt-mobile pull request #98
Opened 2021-04-03 16:27 UTC by onurccn

- waited before finishing up patch request, (updates ui with backend response)
- added global progress indicator to the bottom of appbar

2021-04-04 08:47 UTC, gurolcay commented on gtubt/lib/ui/components/AppBarLinearProgressIndicator.dart
> +import 'package:flutter/material.dart';
dosya isimlendirmesine sadik kalabilir miyiz?

2021-04-04 17:16 UTC, gurolcay approved these changes

2021-04-11 08:49 UTC, gurolcay commented
profile page'de iken edit mode'a gectigimde geri tusuna bastigimda bir onceki state'e donmuyor. @onurccn kontrol edebilir misin?

2021-04-11 08:50 UTC, gurolcay requested changes
profil edit mode'a gecildiginde geri tusuna basilmasi akisi bozuyor.

2021-04-11 11:10 UTC, onurccn commented
> profil edit mode'a gecildiginde geri tusuna basilmasi akisi bozuyor.

dev branchinde de ayni problem mevcut. Sayfalari kontrol ederken onu da cozmus oluruz buyuk ihtimal

2021-04-11 22:02 UTC, gurolcay commented
coflict @onurccn

2021-04-13 16:21 UTC, aErgani approved these changes
LGTM!

2021-04-13 17:28 UTC, onurccn commented
Guncel.

2021-04-14 07:08 UTC, gurolcay approved these changes

2021-04-14 07:08 UTC, merged