Added snackbars
gtubt/gtubt-mobile pull request #99
Opened 2021-04-05 17:55 UTC by aErgani

2021-04-05 18:17 UTC, gurolcay requested changes
Notification Factory kullanilarak yapilmali

2021-04-11 08:51 UTC, gurolcay requested changes
Notification Factory kullanilarak yapilmali

2021-04-13 16:20 UTC, aErgani commented
Güncelledim. Buna ekleme yapılması gerekiyor mu?

2021-04-13 17:15 UTC, gurolcay commented on gtubt/lib/ui/pages/login_form.dart
> +            NotificationFactory.loadingFactory(message: "Logging in...").show(context);
state degisimini kontrol edip BlocConsumer'in listener'inda yapilmali. `state.isLoading` kontrol edebilirsin.

2021-04-13 17:15 UTC, gurolcay commented on gtubt/lib/ui/pages/login_form.dart
> +          if (_authBloc.isBroadcast)
bu if'e ihtiyacimiz yok. dev branchinde olmamasi lazim.
```
NotificationFactory.successFactory(message: "Login Successful").show(context);
context.read<AuthenticationBloc>().add(LoggedIn(context: context));
```
seklinde yapabilir misin?

2021-04-13 17:15 UTC, gurolcay commented on gtubt/lib/ui/style/color_sets.dart
> +  static const snackBarSuccessColor = Color(0xFF4CAF50);
bunlar kullaniliyor mu?

2021-04-13 17:30 UTC, aErgani commented on gtubt/lib/ui/style/color_sets.dart
> +  static const snackBarSuccessColor = Color(0xFF4CAF50);
Hayır kaldırıyorum

2021-04-17 09:08 UTC, gurolcay commented
![](https://github.trello.services/images/mini-trello-icon.png) [Login/SignUp islemleri suresince bildirim vermeli](https://trello.com/c/GPjMk67D/194-login-signup-islemleri-suresince-bildirim-vermeli)

2021-04-18 12:39 UTC, gurolcay approved these changes

2021-04-18 12:39 UTC, merged